<?php

namespace KielPack\LaraLibs\Base\Traits;


use Illuminate\Support\Facades\Auth;

trait BaseModelSaveTrait
{
    public function setUser() {
        $this->user_id = Auth::user()->getAuthIdentifier();
    }

    public function save(array $options = [])
    {
        $this->beforeSave();
        return parent::save($options); // TODO: Change the autogenerated stub
    }



    public function saveWithUser() {
        $this->setUser();
        $this->save();
    }
}