<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Payee extends BaseModel
{
    protected $table = "payees";

    public static function createInstance() {
        return new Payee([
            "payee_code"        =>  "",
            "name"              =>  "",
            "full_address"      =>  "",
            "contact_no"        =>  "",
            "fax_no"            =>  "",
            "email_address"     =>  "",
            "contact_person"    =>  "",
            "payee_type"        =>  "supplier"
        ]);
    }


    protected function beforeSave()
    {
        if($this->payee_code == '') {
            //set payee code
            $type = $this->payee_type;
            if($type == 'supplier') {
                $this->payee_code = "spl-".$this->createNewId();
            }
            else {
                $this->payee_code = "gov-".$this->createNewId();
            }
        }
        return parent::beforeSave(); // TODO: Change the autogenerated stub
    }


}
