<?php


namespace Accounting\app\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;

class AccountingEventServiceProvider extends ServiceProvider
{

    protected $listen = [
        'Accounting\App\Events\OnSaveTransaction' => [
            'Accounting\App\Listeners\SaveTransactionListener'
        ]
    ];

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

}